### ISSUE TITLE
Too few arguments to function

### ISSUE THREAD

**Issue by afbora** [dwightwatson/breadcrumbs#11]
I'm getting error on `dev-master` like that (using nwidart modules):

> Too few arguments to function Modules\Core\Providers\RouteServiceProvider::{closure}(), 1 passed and exactly 2 expected

````php
Breadcrumbs::for('admin.products', function ($trail) {
    $trail->parent('admin.dashboard');
    $trail->add('Products', route('admin.products'));
});

Breadcrumbs::for('admin.products.edit', function ($trail, \Modules\Product\Entities\Product $product) {
    $trail->parent('admin.products');
    $trail->add('Edit', route('admin.products.edit', $product));
});
````

**Comment by afbora** [comment]
I found the issue:

https://github.com/dwightwatson/breadcrumbs/blob/master/src/Breadcrumbs/Generator.php#L69

`$parameters` comes always `array` instead of `null`, so never can't get `$route->parameters`.

**Comment by afbora** [comment]
But still I can't use it with the model. Works with direct parameter:

````php
Breadcrumbs::for('admin.products.edit', function ($trail, int $productId) {
    $trail->parent('admin.products');
    $trail->add('Edit', route('admin.products.edit', $productId));
});
````

**Comment by dwightwatson** [comment]
I can't recommend using `dev-master` because I started working on it then decided it was better off working on a new version. Unfortunately more recently I haven't had the time to work on it so it's stalled.

**Comment by dwightwatson** [comment]
So I don't really have an answer for this I'm afraid. Happy to look at a PR but at some point I'd like to complete working on version 2.0 unless a better option comes along. I've been using Dave James Miller's package for long time, though I note it's recently been deprecated.

**Comment by afbora** [comment]
I started a new project. So I didn't want to use a deprecated package. Hopefully, version 2.0 will be released soon 👀

**Comment by dwightwatson** [comment]
Haha I totally understand where you're coming from. Unfortunately I've been moved to a Rails project for the time being so I need to find some time to squeeze it in.
